# Generated by Django 3.2.5 on 2021-12-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_remove_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'waiting'), (1, 'member'), (2, 'officer'), (3, 'admin'), (4, 'clubowner')], default=0),
        ),
    ]
