# Generated by Django 3.2.5 on 2021-12-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Applicant'), (1, 'Member'), (2, 'Club Officer'), (3, 'Club Owner')], default=0),
        ),
    ]
