# Generated by Django 3.2.5 on 2021-12-10 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_alter_user_experience'),
        ('clubs', '0005_auto_20211210_1534'),
    ]

    operations = [
    ]
