# Generated by Django 3.2.5 on 2021-12-11 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_auto_20211210_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, 'Applicant'), (1, 'Member'), (2, 'Club Officer'), (3, 'Club Owner')], default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='club',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AddField(
            model_name='clubcontract',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.club'),
        ),
        migrations.AddField(
            model_name='clubcontract',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
