# Generated by Django 3.2.5 on 2021-12-10 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_auto_20211208_1849'),
        ('clubs', '0006_merge_20211210_1615'),
    ]

    operations = [
    ]
