# Generated by Django 3.2.5 on 2021-12-10 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_merge_20211210_1904'),
        ('clubs', '0008_remove_user_clubs'),
    ]

    operations = [
    ]
