# Generated by Django 3.2.5 on 2021-12-11 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_merge_0007_merge_20211210_1904_0008_remove_user_clubs'),
        ('clubs', '0009_merge_0007_merge_20211210_1914_0008_remove_user_clubs'),
    ]

    operations = [
    ]
