# Generated by Django 3.2.5 on 2021-12-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_merge_20211211_0002'),
        ('clubs', '0010_merge_20211211_0159'),
    ]

    operations = [
    ]
