# Generated by Django 3.2.5 on 2021-12-11 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_merge_20211211_0159'),
        ('clubs', '0011_alter_user_experience'),
    ]

    operations = [
    ]
